use_frameworks!

$DevelopmentTarget = '15.0'
$RepositoryBaseURL = 'git@github.com:this-is-ritik'

platform :ios, $DevelopmentTarget

install! 'cocoapods',
  :deterministic_uuids => false,
        :share_schemes_for_development_pods => true
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NIWWRDCommon_Example' do
  use_frameworks! :linkage => :static
  inherit! :search_paths
  pod 'NIWWRDCommon', :path => './../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $DevelopmentTarget
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
    config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      if config.name == 'Development'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end
